name: Build and test app
on:
  push:
    #tags:
    #  - 'v*'

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: zephyr-ew25

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: zephyr-ew25
          toolchains: arm-zephyr-eabi

      - name: Create final artifact build directory
        run: |
            mkdir zephyr-ew25-${{ github.ref_name }}

      - name: Build
        working-directory: zephyr-ew25
        run: |
          west build -p -b nrf52840dk/nrf52840 app
          cp -r build/zephyr/* ../zephyr-ew25-${{ github.ref_name }}

      - name: Twister Tests
        working-directory: zephyr-ew25
        shell: bash
        run: |
          west twister -WT tests -v --inline-logs
          cp twister-out/twister* ../zephyr-ew25-${{ github.ref_name }}
          ls -l ../zephyr-ew25-${{ github.ref_name }}
