name: Build and test app
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: zephyr-ew25

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: zephyr-ew25
          toolchains: arm-zephyr-eabi

      - name: Create final artifact build directory
        run: |
            mkdir zephyr-ew25-${{ github.ref_name }}

      - name: Build
        working-directory: zephyr-ew25
        run: |
          west build -p -b nrf52840dk/nrf52840 app
          cp -r build/zephyr/* ../zephyr-ew25-${{ github.ref_name }}

      - name: Twister Tests
        working-directory: zephyr-ew25
        shell: bash
        run: |
          west twister -WT tests -v --inline-logs
          cp twister-out/twister* ../zephyr-ew25-${{ github.ref_name }}

      - name: Coalesce artifacts into tarball
        run: |
          tar cf zephyr-ew25-${{ github.ref_name }}.tar zephyr-ew25-${{ github.ref_name }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: zephyr-ew25-${{ github.ref_name }}
          body: Latest FW release
          draft: false
          prerelease: false

      - name: Upload release
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: zephyr-ew25-${{ github.ref_name }}.tar
          asset_name: zephyr-ew25-${{ github.ref_name }}.tar
          asset_content_type: application/x-tar
