name: Build and test app
on:
  push:
    #tags:
    #  - 'v*'

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: zephyr-ew25

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: zephyr-ew25
          toolchains: arm-zephyr-eabi

      - name: Build
        run: |
          west build -p -b nrf52840/nrf52840 app

